stages:
  - appium


appium_job:
  stage: appium
  tags:
    - ios-host-1
  script:
    - appium --address 0.0.0.0 --port 4723 &
  after_script:
    - python3 telegram_bot/client.py -n appium_job
  cache:
    untracked: true
    key: $CI_COMMIT_REF_NAME-lint
    paths:
      - ./app
    policy: pull
  retry: 2
